version: '3.8'

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=myStrongPassword12#
      - ACCEPT_EULA=Y
    volumes:
      - sqldata:/var/opt/mssql
  webapp:
    container_name: webapp
    build:
      dockerfile: Dockerfile
    image: bazar
    ports:
      - "80:80"
    restart: on-failure
volumes:
  sqldata:
    external: true