version: '3.8'

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=myStrongPassword12#
      - ACCEPT_EULA=Y
    volumes:
      - sqldata:/var/opt/mssql
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: '2GB'
  webapp:
    container_name: webapp
    image: extinshybazarscr.azurecr.io/bazar
    domainname: extinshy
    ports:
      - "80:80"
    restart: on-failure
volumes:
  sqldata:
    driver: azure_file
    driver_opts:
      share_name: sql-volume
      storage_account_name: extinshybazarsa
      
